name: Update README Last Updated Date

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhimanyu003/profile-readme-last-updated@v1.1.0
        with:
          COMMIT_MSG: "🕒 Update last updated"
